services:
    app:
        build: ./app
        ports:
            - "3000:3000"
        environment:
            DB_USER: postgres
            DB_PASSWORD: secret
            DB_NAME: mydb
            DB_HOST: db
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: mydb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres-data:
